trigger:
- main
stages:
  - stage: Build
    pool:
      vmImage: ubuntu-latest
    displayName: Build
    jobs:
      - job: Build
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
          displayName: 'npm install'

        - script: |
            npm run lint
          displayName: 'Lint Code'

        - script: |
            npm run validate
          displayName: 'Validate office.xml file'

        - script: |
            npm run build
          displayName: 'npm build'
          env:
            "REACT_APP_UNSPLASH_API_KEY": $(Unsplash_API_Key)

        - publish: $(System.DefaultWorkingDirectory)/dist/
          displayName: 'Publish DIST folder as artifact'
          artifact: WebApp


  - stage: DeployTest
    pool:
      vmImage: ubuntu-latest
    displayName: Deploy to Test Environment
    dependsOn: Build
    jobs:
      - job: Deploy