trigger:
- main
pool:
    vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        variables:
          prod_url: $[replace(variables['WEBSERVER_URL'], '/', '\/')]
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
          displayName: 'npm install'

        - script: |
            npm run lint
          displayName: 'Lint Code'

        - script: |
            npm run validate
          displayName: 'Validate office.xml file'

        - script: |
            sed -i 's/https:\/\/www.contoso.com\//$(prod_url)/g' ./webpack.config.js
          displayName: Replace Production URL in office manifest

        - script: |
            npm run build
          displayName: 'npm build'
          env:
            "REACT_APP_UNSPLASH_API_KEY": $(Unsplash_API_Key)
        
        - script: |
            mv ./dist/manifest.prod.xml ./dist/manifest.xml
          displayName: Rename manifest.prod.xml to manifest.xml

        - publish: $(System.DefaultWorkingDirectory)/dist/
          displayName: 'Publish DIST folder as artifact'
          artifact: WebApp


  - stage: DeployTest
    displayName: Deploy to Test Environment
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: WebApp
          - task: AzureStaticWebApp@0
            inputs:
              app_location: 'WebApp'
              skip_app_build: true
              verbose: true
              azure_static_web_apps_api_token: '$(Deployment_Token)'