trigger:
- main
pool:
    vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
          displayName: 'npm install'

        - script: |
            npm run lint
          displayName: 'Lint Code'

        - script: |
            npm run validate
          displayName: 'Validate office.xml file'

        - script: |
            npm run build
          displayName: 'npm build'
          env:
            "REACT_APP_UNSPLASH_API_KEY": $(Unsplash_API_Key)
            "Webserver_Url": $(Webserver_Url)
                    
        - script: |
            mv ./dist/manifest.prod.xml ./dist/manifest.xml
          displayName: Rename manifest.prod.xml to manifest.xml

        - publish: $(System.DefaultWorkingDirectory)/dist/
          displayName: 'Publish DIST folder as artifact'
          artifact: WebApp


  - stage: DeployTest
    displayName: Deploy to Test Environment
    dependsOn: Build
    variables:
      skipComponentGovernanceDetection: true
    jobs:
      - job: Deploy
        steps:
          - checkout: none
          - download: current
            artifact: WebApp
          - task: AzureStaticWebApp@0
            inputs:
              workingDirectory: '$(Pipeline.Workspace)'
              skip_app_build: true
              app_location: WebApp/
              azure_static_web_apps_api_token: '$(Deployment_Token)'
        condition: 
              and(
                not(failed()), 
                not(canceled()), 
                not(eq(variables['Build.Reason'], 'PullRequest'))
              )